dist: trusty
sudo: false
language: python
env:
- TOXENV=flake8
- TOXENV=isort
cache: pip
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TOXENV=py27-1.11
  - python: 3.5
    env: TOXENV=py35-1.11
  - python: 3.5
    env: TOXENV=py35-2.1
  - python: 3.5
    env: TOXENV=py35-2.2
    dist: xenial
    sudo: true
  - python: 3.6
    env: TOXENV=py36-1.11
  - python: 3.6
    env: TOXENV=py36-2.1
  - python: 3.6
    env: TOXENV=py36-2.2
    dist: xenial
    sudo: true
  - python: 3.6
    env: TOXENV=py36-3.0
    dist: xenial
    sudo: true
  - python: 3.6
    env: TOXENV=py36-3.1
    dist: xenial
    sudo: true
  - python: 3.6
    env: TOXENV=py36-master
    dist: xenial
    sudo: true
  - python: 3.7
    env: TOXENV=py37-2.1
    dist: xenial
    sudo: true
  - python: 3.7
    env: TOXENV=py37-2.2
    dist: xenial
    sudo: true
  - python: 3.7
    env: TOXENV=py37-3.0
    dist: xenial
    sudo: true
  - python: 3.7
    env: TOXENV=py37-3.1
    dist: xenial
    sudo: true
  - python: 3.7
    env: TOXENV=py37-master
    dist: xenial
    sudo: true
  - python: 3.8
    env: TOXENV=py38-2.1
    dist: xenial
    sudo: true
  - python: 3.8
    env: TOXENV=py38-2.2
    dist: xenial
    sudo: true
  - python: 3.8
    env: TOXENV=py38-3.0
    dist: xenial
    sudo: true
  - python: 3.8
    env: TOXENV=py38-3.1
    dist: xenial
    sudo: true
  - python: 3.8
    env: TOXENV=py38-master
    dist: xenial
    sudo: true
  - python: 3.9
    env: TOXENV=py39-2.1
    dist: xenial
    sudo: true
  - python: 3.9
    env: TOXENV=py39-2.2
    dist: xenial
    sudo: true
  - python: 3.9
    env: TOXENV=py39-3.0
    dist: xenial
    sudo: true
  - python: 3.9
    env: TOXENV=py39-3.1
    dist: xenial
    sudo: true
  - python: 3.9
    env: TOXENV=py39-master
    dist: xenial
    sudo: true
  allow_failures:
  - env: TOXENV=py36-master
  - env: TOXENV=py37-master
  - env: TOXENV=py38-master
  - env: TOXENV=py39-master
install:
- pip install tox coveralls
script:
- tox
after_success:
- if [ -f .coverage ]; then coveralls; fi
